version: '3'
services:
  was:
    container_name: gifthub-was
    image: repl4242/gifthub-was:${IMAGE_TAG}

    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ~/resources:/opt/app